//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.25 at 06:09:43 PM CET 
//


package _Aufgabe4;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rezept }
     * 
     */
    public Rezept createRezept() {
        return new Rezept();
    }

    /**
     * Create an instance of {@link Rezept.Comments }
     * 
     */
    public Rezept.Comments createRezeptComments() {
        return new Rezept.Comments();
    }

    /**
     * Create an instance of {@link Rezept.Zutaten }
     * 
     */
    public Rezept.Zutaten createRezeptZutaten() {
        return new Rezept.Zutaten();
    }

    /**
     * Create an instance of {@link Rezept.Pictures }
     * 
     */
    public Rezept.Pictures createRezeptPictures() {
        return new Rezept.Pictures();
    }

    /**
     * Create an instance of {@link Rezept.Zubereitung }
     * 
     */
    public Rezept.Zubereitung createRezeptZubereitung() {
        return new Rezept.Zubereitung();
    }

    /**
     * Create an instance of {@link Rezept.Comments.Comment }
     * 
     */
    public Rezept.Comments.Comment createRezeptCommentsComment() {
        return new Rezept.Comments.Comment();
    }

    /**
     * Create an instance of {@link Rezept.Zutaten.Zutat }
     * 
     */
    public Rezept.Zutaten.Zutat createRezeptZutatenZutat() {
        return new Rezept.Zutaten.Zutat();
    }

    /**
     * Create an instance of {@link Rezept.Pictures.Pic }
     * 
     */
    public Rezept.Pictures.Pic createRezeptPicturesPic() {
        return new Rezept.Pictures.Pic();
    }

}
